bot:
  url: https://api.telegram.org/bot
  name: FirstTestingBot
  chatId: -1001238385079
  token: 1574801869:AAErCVUSFkL7aAxyvNNbDAsLy3vUov-yGs0

server:
  port: 80

#spring.datasource.username: name
#spring.datasource.password: password
#spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
#spring.jpa.hibernate.ddl-auto: create
