spring.h2.console.enabled: true
spring.h2.console.path: /h2-tick
spring.datasource.url: jdbc:h2:mem:tickdb
spring.datasource.driverClassName: org.h2.Driver
spring.datasource.username: name
spring.datasource.password: password
spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto: create
port: 8080